{% set name = "hydromt" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydromt-{{ version }}.tar.gz
  sha256: f9cb56e54c17fbf52c01fb08011e5a887956d48e6e6595aff735fc1e3a142e6a

build:
  number: 0
  noarch: python
  entry_points:
    - hydromt = hydromt.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
  run:
    # since noarch: python doesn't allow us to do fsspec[http]
    # we have to manually list the extra dependencies the http
    # features of fsspec pulls in. 
    - affine
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - bottleneck
    - click
    - dask
    - fsspec
    - geopandas >=0.10
    - importlib-metadata
    - mercantile
    - netcdf4
    - numba
    - numpy
    - packaging
    - pandas
    - pooch
    - pyarrow
    - pydantic ~=2.4
    - pydantic-settings ~=2.2
    - pyflwdir >=0.5.4
    - pyogrio >=0.6
    - pyproj
    - pystac
    - python >={{ python_min }},<3.14
    - pyyaml
    - rasterio
    - requests
    - rioxarray
    - scipy
    - shapely >=2.1.0
    - tomli
    - tomli-w
    - universal_pathlib >=0.2
    - xarray
    - xmltodict
    - xugrid >=0.9.0
    - zarr >=2,<3
test:
  imports:
    - hydromt
    - hydromt.cli
  commands:
    - pip check
    - hydromt --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hydromt/
  summary: 'HydroMT: Build and analyze models like a data-wizard!'
  doc_url: https://deltares.github.io/hydromt/stable/
  dev_url: https://github.com/Deltares/hydromt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalmijn
    - deltares-service-account
    - savente93
    - DirkEilander
    - hboisgon
    - dalmijn
