{% set name = "hydromt" %}
{% set version = "0.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt-{{ version }}.tar.gz
  sha256: 4df2df5a36b67c2a11e339ea167bd3188a492aac6a23fa263b0442c402b7031c

build:
  number: 0
  noarch: python
  entry_points:
    - hydromt = hydromt.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.9
  run:
    - affine
    - bottleneck
    - click
    - dask
    - fsspec
    - geopandas >=0.10
    - importlib_metadata
    - mercantile
    - netcdf4
    - numba
    - numpy >=1.20
    - packaging
    - pandas
    - pydantic ~=2.4
    - pyflwdir >=0.5.4
    - pyogrio >=0.6
    - pyproj
    - pystac
    - python >=3.9
    - pyyaml
    - rasterio
    - requests
    - rioxarray
    - scipy
    - shapely >=2.0.0
    - tomli
    - tomli-w
    - universal_pathlib <2.0
    - xarray
    - xmltodict
    - zarr
test:
  imports:
    - hydromt
    - hydromt.cli
  commands:
    - pip check
    - hydromt --help
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt/
  summary: 'HydroMT: Build and analyze models like a data-wizard!'
  dev_url: https://github.com/Deltares/hydromt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - savente93
    - DirkEilander
    - hboisgon
