{% set name = "hydromt" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydromt-{{ version }}.tar.gz
  sha256: 24816f5fca677531b31ec39bb789d840b1beb0d5c852fa5c799a42292a261b83

build:
  number: 0
  noarch: python
  entry_points:
    - hydromt = hydromt.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.8
  run:
    - affine
    - bottleneck
    - click
    - dask-core >=2.3
    - entrypoints
    - gdal >=3.1
    - geopandas >=0.8
    - netcdf4
    - numba
    - numpy
    - openpyxl
    - pandas
    - pyflwdir >=0.4.7
    - pygeos
    - python >=3.8
    - rasterio
    - requests
    - scipy
    - xarray
    - zarr

test:
  imports:
    - hydromt
    - hydromt.cli
  commands:
    - pip check
    - hydromt --help
  requires:
    - pip

about:
  home: https://pypi.org/project/hydromt/
  summary: 'HydroMT: Build and analyze models like a data-wizard!'
  dev_url: https://github.com/Deltares/hydromt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
